### ISSUE TITLE
Uninstalled App causes Internal Server Error

### ISSUE THREAD

**Issue by issc29** [osowskit/atlassian-github-app-addon#10]
When you uninstall the App from GitHub but already had a session set up in the plugin, the plugin sends an Internal Server Error

<img width="282" alt="screen shot 2017-07-21 at 10 46 34 am" src="https://user-images.githubusercontent.com/6920330/28468828-250fb85a-6e02-11e7-81aa-829bd26533d1.png">

The only way to fix this is to clear the cookie so you can reinstall the app in GitHub

<img width="285" alt="screen shot 2017-07-21 at 10 49 45 am" src="https://user-images.githubusercontent.com/6920330/28468905-71923cac-6e02-11e7-9992-20fbce4e6037.png">

may want to fix this in PR #8

**Comment by osowskit** [comment]
@issc29 thanks for the report. This is logged as #3

**Comment by issc29** [comment]
Duplicate of #3

**Comment by margani** [comment]
Still having issues with stopping the trial.
![image](https://user-images.githubusercontent.com/46093/177750664-21e3a91e-2fa2-439b-9f3a-b9c8e67a512a.png)

I cannot uninstall the app because it says subscription still exists. I don't want to be billed after the trial ends.
