### ISSUE TITLE
Plugin does not work on Firefox

### ISSUE THREAD

**Issue by powerman** [osowskit/atlassian-github-app-addon#12]
I've just installed it, but it doesn't work.

- I've installed JIRA plugin.
- I've installed GitHub addon.
  - I've allowed access only to one of my organizations, for all repos.
- I've then open some JIRA issue:
  - It shows "Connect to GitHub" and "clear settings" links, but also it show "Add-on is not responding. Wait or cancel?" message.
  - I'm clicking on "Connect to GitHub" and after a couple of redirects I get text "false" in place of "Connect to GitHub" and "clear settings" links.
  - On reloading issue I'm able to see "Connect to GitHub" and "clear settings" links once again.

I've checked Firefox's network requests, and it looks like it gets 404 on https://atlassian-github-app-addon.herokuapp.com/atlassian-connect/all.js - maybe this is the cause.

**Comment by osowskit** [comment]
@powerman I'll take a look now.

**Comment by osowskit** [comment]
@powerman thanks for reporting this. It looks like this is an issue with how Firefox handles cross site scripting requests. `request rejected (bad origin)` I'll see if I can modify the source to support Firefox browsers. For the time being, can you confirm this works on Chrome?

**Comment by osowskit** [comment]
@powerman it turns out to be a JS error. I've pushed a fix to production. Let me know if you have any more trouble.

**Comment by powerman** [comment]
I can confirm it works in Chromium.
But in Firefox/Linux it still doesn't work:

- I still see "Add-on is not responding. Wait or cancel?".
- After clicking "Connect to GitHub" after auto-opening/closing new tab I get same page - i.e. I still see the "Connect to GitHub" link (previously I get text "false" in place of this link, so, yes, you've partially fixed this issue).

### Offtopic

After trying this plugin in Chromium I've realized it doesn't actually fit our needs. I've expected something similar to JIRA's native "Create branch" feature for BitBucket, and I really needs more than this plugin able to do at this moment:

- We're using several repos for same JIRA project, so it's better to ask about repo each time (or let user select more than one repo, or, even better, autodetect all github repos connected to this project) than just remember last choice and require "clear settings" each time we wanna create branch in another repo.
- It would be nice if auto-generated branch name will include (part of) issue's summary after issue ID.
- It would be nice if user will be able to edit auto-generated branch name before it will be created.

**Comment by osowskit** [comment]
@powerman thanks for the feedback. I've moved your feature request to support multiple repositories to #13 and can notify you if I can figure out how to gracefully add this.

**Comment by powerman** [comment]
Thanks. No needs to notify - I've subscribed to #13.

**Comment by osowskit** [comment]
Calling methods between two windows did not work on Ubuntu Firefox. Replaced this to force a page reload directly.

**Comment by osowskit** [comment]
> It would be nice if auto-generated branch name will include (part of) issue's summary after issue ID. It would be nice if user will be able to edit auto-generated branch name before it will be created.

I've captured this feedback in https://github.com/osowskit/atlassian-github-app-addon/issues/20.
