### ISSUE TITLE
I am adding GitHub but there is no repositories

### ISSUE THREAD

**Issue by zavara** [osowskit/atlassian-github-app-addon#16]
Hi,
I am using Jira Cloud and I have install addon. 
I have completed all steps like in manual. The last one was:
Applications->INTEGRATIONS->DVCS accounts-> Link Github account -> SUCCESS 
and as the result no repositories below. Actually I have repositories and they are private.
I have attached screen, please help.
![image](https://user-images.githubusercontent.com/12083259/32537080-d203dbd2-c469-11e7-9f4c-1b55b1feb4f6.png)

Thanks!

**Comment by osowskit** [comment]
@zavara 👋 thanks for installing the addon. This addon works separately from the DVCS integration.

After installing the addon, you should be able to see a new a new panel inside of a JIRA. This will ask for your credentials and allow you to select a Repository. 👇 

<img width="370" alt="screen shot 2017-11-11 at 8 32 49 pm" src="https://user-images.githubusercontent.com/768821/32695979-8d85ff68-c71f-11e7-8d54-b65dd8b1e892.png">

**Comment by zavara** [comment]
Thanks!

**Comment by pzontrop** [comment]
I also can't find this panel anywhere. Perhaps someone could describe it in the readme?

**Comment by osowskit** [comment]
> I also can't find this panel anywhere. Perhaps someone could describe it in the readme?

@pzontrop Is there anything I could add specifically to make this clearer? Did you install the Marketplace extension https://marketplace.atlassian.com/1217260

**Comment by pzontrop** [comment]
The thing that got me confused was that the panel only shows up if you open the issue. Not in the issue slider you see on the board.

I also set up the github DVCS accounts which made this plugin work for me. Now however i found out that it doesn't fully meet my requirements (yet). I have 2 repositories (one front-end and one backend) linked to the project which is not yet possible with this plug-in. I would also love to have the issue title in the branch name. I wouldn't mind helping out with those features but after checking your code I am afraid I wouldn't know how. Good luck with the plugin!

**Comment by osowskit** [comment]
> The thing that got me confused was that the panel only shows up if you open the issue. Not in the issue slider you see on the board.

@pzontrop can you attach a screenshot and description of which pages aren't showing the plugin.  I may be able to add that.

> I have 2 repositories (one front-end and one backend) linked to the project which is not yet possible with this plug-in.

I've logged #13 to support multiple repositories but would like more information about how you would like to 1) select multiple repositories and 2) how you want to create branches.

**Comment by osowskit** [comment]
I've pushed a change to allow multiple repositories to production. Let me know if you notice any unexpected behavior.
