### ISSUE TITLE
Add support for GitHub Enterprise

### ISSUE THREAD

**Issue by osowskit** [osowskit/atlassian-github-app-addon#17]
Support when GitHub Apps are supported on GitHub Enterprise.

**Comment by osowskit** [comment]
**Considerations**
* Multiple Internal GHE instances
* Trusted Environment - Segregation of information not required
  * Store Commit/Repo
  * Webhooks to add commits in-flight

**Comment by mcascone** [comment]
Hi, does this mean this does not currently work with GHE behind a firewall?

**Comment by osowskit** [comment]
> Hi, does this mean this does not currently work with GHE behind a firewall?

@mcascone correct. However, you could host this software yourself and configure it to work with your instance of GHE. Let me know if you're interested in setting this up.

**Comment by mcascone** [comment]
I'm hesitant to get into self-hosting anything, but I'm not going to dismiss it out of hand. What does it look like?

Thanks, Max

**Comment by osowskit** [comment]
@mcascone the steps are roughly:
 1. Clone and deploy source to Heroku
 1. Create a GitHub App on your GHE instance
 1. Update the source code to point [Octokit to your GHE API](https://github.com/octokit/octokit.rb#working-with-github-enterprise) endpoint 
 1. Create a private Atlassian Add-on with a custom identifier and install to your JIRA instance
