### ISSUE TITLE
Plug-in Only Allowing One Branch Per JIRA Ticket

### ISSUE THREAD

**Issue by tabruno** [osowskit/atlassian-github-app-addon#23]
Is this by design or a bug ?  Seems the former.  Once a branch is created off the ticket the "Create Branch" option disappears from the Pane.  Since the plug-in's convention is to give the branch the same name as the ticket, I can see that prohibits multiple branches but that could be overcome w/ one extra character for numbering.   Just a thought

**Comment by osowskit** [comment]
@tabruno thanks for the feedback. I've logged https://github.com/osowskit/atlassian-github-app-addon/issues/20 to track customizing the creation of branch names and believe that this could include creating more than one branch.

Can you describe your development process that demonstrates how multiple branches are used to track and release code?

**Comment by tabruno** [comment]
Thanks again Tom O. for the quick response.  Our process (and need) stems from uncommon times where-in a work task might need to be shared by multiple developers (probably no more than two). If (as an example) the assigned JIRA task is to "change firmware to add new sensor parameters", but there is more than one sensor, we may have one firmware developer change source and unit test (for sensor 1) while another developer does so for sensor 2).  

Noted .. We could certainly create new JIRAs to cover this case but our level of "task granularity" may not always be that detailed.

**Comment by osowskit** [comment]
There is a workaround by creating subtasks for each work item, though realize this may not be ideal. I think this is a very valid use case. However, I don't have plans on adding this in the short term. I'm closing this for now but will keep this in mind if I rework the branch creation strategy.
