### ISSUE TITLE
Support the plugin on JIRA standalone

### ISSUE THREAD

**Issue by mkj28** [osowskit/atlassian-github-app-addon#24]
Looks to be for Cloud-only. Add support for standalone/on-premise JIRA installs, please.

**Comment by osowskit** [comment]
Thanks for the feedback @mkj28. The plugin currently makes assumptions to simplify the logic that isn't suitable for a number of projects or workflows. However, it should be easy for you to deploy a copy of this plugin for your own instance. I have contacted you directly to help discuss what modifications need to be made to achieve this.

**Comment by gheim-dfa** [comment]
Hi @osowskit , I have a similar use-case of wanting to implement this plugin on an on-prem jira instance, could you contact me on how I could make this possible? Thank you

**Comment by osowskit** [comment]
@gheim-dfa given the on-prem product is being discontinued, I won't be able to assist with this. If you are able to resolve this, feel free to open a PR to help others with this

**Comment by gheim-dfa** [comment]
Atlassian is still providing support for server instances until February 2, 2024. Could you please at least point me in the right direction to help me and potentially others who may want to implement this until maybe switching to a cloud instance? Given the loss of support is 3 years away, I'm sure others may still want a solution for this until then
