### ISSUE TITLE
Customize branch name in branch creation

### ISSUE THREAD

**Issue by taxpon** [osowskit/atlassian-github-app-addon#25]
Created  branches through this add-on have each JIRA's issue number as the branch name. I would like to customize branch name like feature/XXXX so that I can follow the git-flow rule.

Thanks in advance.

**Comment by osowskit** [comment]
👋 @taxpon - This is a great request and a duplicate of #20. Would every branch be named `feature/XXX` or are there other prefixes you would want to use?

**Comment by taxpon** [comment]
@osowskit Oh, sorry for dup. Currently I'd like to use `feature/xxx` only using this add-on.

**Comment by osowskit** [comment]
I like the idea of a prefix and may get to this in the next few weeks. Closing in favor of #20
