### ISSUE TITLE
Add Support for JIRA server

### ISSUE THREAD

**Issue by osowskit** [osowskit/atlassian-github-app-addon#26]
I have received a few requests to support JIRA server. Since I don't have access to an instance, I am blocked on implementing support for this.

My assumption is that this is mostly a packaging exercise. Let me know if you have access to a JIRA Server environment and are willing to help package this add on.

**Comment by CICDth** [comment]
Yes please. I have access JIRA server. could you please help us the package this add on

**Comment by CICDth** [comment]
> I have received a few requests to support JIRA server. Since I don't have access to an instance, I am blocked on implementing support for this.
> 
> My assumption is that this is mostly a packaging exercise. Let me know if you have access to a JIRA Server environment and are willing to help package this add on.

Yes please. I have access JIRA server. could you please help us the package this add on

**Comment by m-weintraub** [comment]
Hi.  I also have access to a Jira server.  I'd be glad to pitch in.  Does anyone else want to work on this?
