### ISSUE TITLE
Handle uninstalled App

### ISSUE THREAD

**Issue by osowskit** [osowskit/atlassian-github-app-addon#3]
Users that uninstall the App will get a 500 error unless the Installation ID is cleared.

**Comment by osowskit** [comment]
Also investigating issues where uninstalling the app doesn't expire the access token.

**Comment by osowskit** [comment]
I've reworked the logic. it's fixed on my production branch and need to merge this back to master...

**Comment by margani** [comment]
Still having issues with stopping the trial.
![image](https://user-images.githubusercontent.com/46093/177750664-21e3a91e-2fa2-439b-9f3a-b9c8e67a512a.png)

I cannot uninstall the app because it says subscription still exists. I don't want to be billed after the trial ends.

**Comment by margani** [comment]
I cleared the settings and tried again, it is successfully stopped and I could uninstall it.
