### ISSUE TITLE
Add support for organization repos

### ISSUE THREAD

**Issue by a-jay85** [osowskit/atlassian-github-app-addon#30]
I'm a user with one personal repo, but I have collaborator access to my work's repos as a part of their Github organization. My work admin installed the GitHub App Plugin for Jira, and I installed the JIRA-bot app in my GitHub account. However, when I try to create a branch, the app only sees my personal repo and none of my work's repos. Tried this with two other co-workers who have owner permissions on their work repos and they couldn't see their work repos either.

Would it be possible to support creating branches in organization repos that a user has access to? I'd love to use this plugin for work. Thanks!

**Comment by osowskit** [comment]
@a-jay85 thanks for the report. The [jira-bot](https://github.com/apps/jira-bot) application should be  installed on the GitHub Organization to have access to those repositories.. Could you request someone in that GitHub Organization install the application?

**Comment by a-jay85** [comment]
Sorry, just saw this! I'll request that right now and report back once its done. Thanks for the clarification!
