### ISSUE TITLE
Add support for +30 Repositories

### ISSUE THREAD

**Issue by Burkraith** [osowskit/atlassian-github-app-addon#31]
Hi, we have a lot of repositories inside github and when we load all repositories we don't see all repositories inside the list only a few. Are we doing something bad in the config's side or is the normal behaviour of the plugin?

Thanks!

**Comment by osowskit** [comment]
@Burkraith this is likely a bug. How many repositories would you expect to see?

**Comment by Burkraith** [comment]
Hi, thanks for your quick answer
We have like 150 repos and we can see only 30.

**Comment by osowskit** [comment]
Thanks for the report. I'll try pushing out a fix today.

**Comment by Burkraith** [comment]
Thank you very much!

**Comment by osowskit** [comment]
@Burkraith I've pushed a change into production that should support this. Let me know if you have any trouble with this

**Comment by Burkraith** [comment]
I've been on vacation sorry, it's working very good.

Thank you!
