### ISSUE TITLE
Allow selection of branch source

### ISSUE THREAD

**Issue by gasrios-cit** [osowskit/atlassian-github-app-addon#33]
Hi,

When creating bug fix branches, we need to use a "release" branch as source, not master.

Is it possible to add a "select source to branch from" to the plugin? Ideally this should be a drop-down like selection, but even a text field would work.

Thanks!

**Comment by gasrios-cit** [comment]
@osowskit When we release, say, version "1.4.0", we create branch "1.4.X" (where "X" stands for itself, ie, is not a placeholder).

When we start working on a new bug, we branch a hotfix branch from "1.4.X", then merge back into it once we are done.

Or, to give a direct answer to your question, yes, the branch names are reliable and follow the pattern "A.B.X", where A and B are numbers, and X stands for itself.

**Comment by osowskit** [comment]
@gasrios-cit I think this request showcases the diversity of software development/release practices and agree this *should* be supported. I have no short-term plans to enable this workflow to keep the UI as simple and responsive as possible. 

However, this repository contains the source code necessary to allow developers to extend this to fit your specifications. Please fork this repository and reach out to me if you would like help implementing this.
