### ISSUE TITLE
Invalid postInstallRedirect in atlassian-connect.json

### ISSUE THREAD

**Issue by ngocdaothanh** [osowskit/atlassian-github-app-addon#39]
Currently https://atlassian-github-app-addon.herokuapp.com/atlassian-connect.json is different from the [source code](https://github.com/osowskit/atlassian-github-app-addon/blob/master/public/atlassian-connect.json).

It contains this additional entry:

```json
"postInstallRedirect": {
      "key": "redirect",
      "url": "https://github.com/apps/jira-bot/installations/new"
}
```

It's only valid for Bitbucket, thus invalid for Jira:
https://developer.atlassian.com/cloud/bitbucket/modules/post-install-redirect/

**Comment by osowskit** [comment]
Thank you for reporting this. I've rolled back this change.
