### ISSUE TITLE
Unable to create a branch in my connected repository

### ISSUE THREAD

**Issue by dkrawec** [osowskit/atlassian-github-app-addon#41]
![screen shot 2018-10-04 at 4 45 21 pm](https://user-images.githubusercontent.com/28032529/46502025-18b17c80-c7f5-11e8-8114-87c745e48e8c.png)

I recently installed the add-on to connect github repos to jira issues.

The add-on appears to be failing at the point of clicking "create a branch in .... repository". I click, and nothing happens.

Please see screenshot with console image for info. Thanks!

**Comment by osowskit** [comment]
@dkrawec many issues can be resolved by [clearing the settings](https://atlassian-github-app-addon.herokuapp.com/). If that doesn't work, could you email me the browser information, name of the  JIRA hostname, and a Issue name to `osowskit@osowskit.com`?

**Comment by osowskit** [comment]
It turns out that this was due to an incorrect assumption and never worked for Private repositories. I've modified the permissions on the GitHub App which should send an email to users and Org Owners to grant the app `:read` access to Pull Requests.

✨ 🌈 Thanks for reporting this!
