### ISSUE TITLE
Would this also work with Gitlab?

### ISSUE THREAD

**Issue by emilyspitzer** [osowskit/atlassian-github-app-addon#44]
Does this solution work for GitLab in addition to GitHub?

**Comment by osowskit** [comment]
No.

This relies on using GitHub Apps which are separate from traditional OAuth applications. The API requests should be similar but the authentication would require a rewrite of much of the code. 

That said, if anyone want to fork this repo and build the integration, I will gladly provide guidance.

**Comment by emilyspitzer** [comment]
Ok thanks! I will follow up with my team to see if this is something they want to build.
