### ISSUE TITLE
Not working with Chrome browser, but working with Firefox

### ISSUE THREAD

**Issue by maxi-marufo** [osowskit/atlassian-github-app-addon#45]
Hi Thomas! The app works great with Firefox, but it's not working for me with Chrome browser. When I click on GitHub Development, it says "We're having trouble connecting to GitHub Development. Try contacting the developer for support.". Do you know what could be happening? I guess maybe something with the cookies? Thanks!

**Comment by osowskit** [comment]
I will try reproducing this later today. Could you provide the version of chrome, OS, and any errors that show up in the developer console? A hard reset may help.

Separately visiting https://atlassian-github-app-addon.herokuapp.com/logout might help

**Comment by osowskit** [comment]
Hey @maxi-marufo. Let me know if you have any additional information that can help me reproduce this

**Comment by osowskit** [comment]
@max-marufo any chance you could help me resolve this?
