### ISSUE TITLE
Error when connecting to panel

### ISSUE THREAD

**Issue by gigecogary** [osowskit/atlassian-github-app-addon#47]
<img width="319" alt="Screen Shot 2019-10-21 at 2 59 37 PM" src="https://user-images.githubusercontent.com/56096213/67234621-6c4c3380-f413-11e9-939f-6e475406e36d.png">

**Comment by osowskit** [comment]
@gigecogary thanks for reporting this. Can you visit https://atlassian-github-app-addon.herokuapp.com/debug and email me the output : osowskit@osowskit.com

Separately, you could also try logging out https://atlassian-github-app-addon.herokuapp.com/logout and/or re-installing the plugin.

Additional questions:
- Does this happen for other users of Jira
- Have you linked your GitHub account
- Does this happen on other computers
- Do you have Javascript enabled
- Do you have an ad blocker enabled? Does it work in incognito mode

**Comment by osowskit** [comment]
I believe this was sorted out offline.
