### ISSUE TITLE
Authorizing More Than One Account

### ISSUE THREAD

**Issue by ilgityildirim** [osowskit/atlassian-github-app-addon#48]
I'm using JIRA + Github with the same email address. I'm member of multiple JIRA accounts. I authorized to one organization and now, for my personal JIRA, I can't even choose to authorize my own account.

How can I authorize the app to see my own branches as well as another organization's accounts?

**Comment by osowskit** [comment]
This plugin will allow you to create/view branches on any repository that 1) you have access to and 2) the app is ou installed on. To install this on multiple GitHub accounts, please visit this page https://github.com/apps/jira-bot/installations/new

**Comment by ilgityildirim** [comment]
@osowskit it would be much convenient to have this link somewhere visible.

**Comment by osowskit** [comment]
Great feedback. Do you have a suggestion on where you would have expected to see this?

**Comment by ilgityildirim** [comment]
I'd say where we do select a repository, right next to "clear settings" and "cancel" links.
Another place I'd think it would be useful is to add right after first time selection to give option to select more just in case.
