### ISSUE TITLE
App is not responding - cannot setup app in 'Get Started'

### ISSUE THREAD

**Issue by SemionPar** [osowskit/atlassian-github-app-addon#49]
Just installed the app in cloud Jira, but can't get past 'Get Started' screen, the app won't load:
![image](https://user-images.githubusercontent.com/12086191/69656176-5c5dea00-1078-11ea-9065-5f15215d930d.png)
Tried both chrome incognito and safari.

I followed the advice from readme and manually connected the bot using separate browser tab, but the repository selection screen was off and I could only select one repository from an org.

**Comment by SemionPar** [comment]
Actually, while the screen made me believe I could select only one repo from the org, I could create branches in all of them, so it works after all, maybe just not as pleasant to use as one would expect. 
Feel free to close this if you don't think you need to do anything about it.

**Comment by osowskit** [comment]
Thanks for reporting this. I'll revert a change I made a few weeks back
that may be causing this issue

**Comment by bilalatsoter** [comment]
Hi, I'm experiencing this issues and not sure how to get around it.

**Comment by osowskit** [comment]
@bilalatsoter sorry to hear. Are there any errors in the browser error console?  Does visiting https://atlassian-github-app-addon.herokuapp.com/logout help?

**Comment by bilalatsoter** [comment]
THanks for responding so quickly. Just seeing that. I don't see anything in any ticket for creating a branch.
![image](https://user-images.githubusercontent.com/57913751/70487006-dc953e00-1ac1-11ea-843a-c09b0de21d5d.png)

**Comment by osowskit** [comment]
Could you open the logout link in a separate window and follow the prompts outside of Jita?
