### ISSUE TITLE
GitFlow branching not used despite existing yaml file

### ISSUE THREAD

**Issue by vgeirnaert-emakina** [osowskit/atlassian-github-app-addon#51]
I've recently added this plugin to a repo and it can create branches from master straight up in our repo. However, I'd like it to use gitflow, so create branches from develop and with the name feature/SCC-xxx instead of SCC-xxx.

I created a file .github/jira-bot.yaml with the contents 'branch_pattern: 1' in the root of our repo in the master branch, according to the documentation, and re-added the repo, but it's still creating branches as if this file does not exist and not following gitflow.

Is there something more that needs to be done?

**Comment by osowskit** [comment]
I'm sorry to hear you are having trouble. Does this repo have a different default branch set (not `master`) and, if you create the yaml file on a new repo and add it, does it work in that case?

**Comment by mjvdvlugt** [comment]
I had the same issue, it took some tinkering and testing but now I found out that when logging in as a collaborator on the project it does follow the branch pattern. Still: logging in as the repo owner it does not! Below a screenshot when logged in as repo admin:
<img width="399" alt="Schermafbeelding 2020-03-04 om 12 01 35" src="https://user-images.githubusercontent.com/22216538/75873276-ef44b800-5e0f-11ea-8a0d-87e7f062cea3.png">

And the result of clicking "Create a branch" as a collaborator:
<img width="349" alt="Schermafbeelding 2020-03-04 om 12 03 45" src="https://user-images.githubusercontent.com/22216538/75873533-57939980-5e10-11ea-9eca-b795a066cc83.png">
<img width="995" alt="Schermafbeelding 2020-03-04 om 12 05 33" src="https://user-images.githubusercontent.com/22216538/75873597-75f99500-5e10-11ea-8905-673e2a6d91eb.png">

So now it did create the correct branch name, but it doesn't provide the handy links in the Jira pane.

**Comment by osowskit** [comment]
@mjvdvlugt any chance you could add me as a collaborator to that repo (or one with a similar problem)?

**Comment by mjvdvlugt** [comment]
Yes! I created a test repo, set it up in the same way (adding the .github/jira-bot.yaml ), gave the plugin access to that repo, tested it as a collaborator (now that also doesn't seem to work) and added you as a collaborator. Hope this helps you!!

**Comment by osowskit** [comment]
Thanks for the access. I've been able to reproduce this and will take a look sometime this week.

**Comment by osowskit** [comment]
@mjvdvlugt this should be working now. Thanks ✨🚀 for helping me reproduce and debug this. Let me know if you have any issues
