### ISSUE TITLE
Jira Triggers are not working if GitHub App also installed 

### ISSUE THREAD

**Issue by hendrikschneider** [osowskit/atlassian-github-app-addon#52]
When I am creating a new branch workflow triggers won't be triggered. I created the trigger that the transaction should be done when a new branch is created. 

I had some problems there, because not the correct email address was used to create a commit or pull request. It must be the same email address as the jira uses for his account. Maybe an option to specify the email address used would be helpful

**Comment by osowskit** [comment]
@hendrikschneider this workflow trigger sounds amazing. Could you describe how this works a bit more?

> I had some problems there, because not the correct email address was used to create a commit or pull request

All interaction on your account will be by a jira-bot user that cannot be changed. Let's brainstorm a workaround since there is a chance we can get what you are looking for

**Comment by hendrikschneider** [comment]
Workflow triggers are explained here: https://confluence.atlassian.com/adminjiracloud/configuring-workflow-triggers-776636696.html#Configuringworkflowtriggers-eventsTriggerevents

You can add one easily, if you click on a transaction in your workflow and then triggers. Then you can add that this one should be executed if something happens such as a pull request.

What I setup is that a ticket automatically moves from "In Progress" to "Code Review" when a pull request is created. That one works amazing and is really cool. 

What I thought of is that a ticket automatically moves automatically from Todo -> In Progress when I create a branch from the ticket.

Could it be possible to directly access the jira api and update the status of the ticket? Could also be possible to create a config files where a state and it's action will be described.

`{
'todo': 'triggerName'
}`

**Comment by osowskit** [comment]
Thanks for the wiki. I agree that this should be working based on the docs and that it should require an email address to map to your Jira account. I would recommend reaching out to their support to help debug why this isn't working

**Comment by grawl-aw** [comment]
i faced the same issue. Jira doesn't recognize a new branch created with your addon but when a branch is created directly on github it is recognized immediately. The branch created using this addon only gets recognized in Jira when we create a pull request on github. Any idea ?

**Comment by osowskit** [comment]
> but when a branch is created directly on github it is recognized immediately

Could you describe this a bit more? What connection/tool is linking Jira and GitHub to pick this up?

**Comment by grawl-aw** [comment]
Im using the github app (https://marketplace.atlassian.com/apps/1219592/github-for-jira?hosting=cloud&tab=overview) which doesn't let me create branches. This app track for new commits, branches ... But when the branch is created with your app it doesn't triggers

**Comment by osowskit** [comment]
> But when the branch is created with your app it doesn't triggers

I believe this is a restriction that GitHub has enforced to prevent GitHub apps reacting to actions from other GitHub apps. I believe that contacting that app's support would be able to confirm this.

**Comment by grawl-aw** [comment]
I understand, thank you! so this issue doesn't have any solution, right ?

**Comment by osowskit** [comment]
> I understand, thank you! so this issue doesn't have any solution, right ?

This add on currently doesn't have direct access to Jira so wouldn't be able to easily accomplish this. I'll try to think of a creative solution but would recommend asking GitHub (the owners of that app).
