### ISSUE TITLE
App is not responding from JIRA using Safari

### ISSUE THREAD

**Issue by dattachandan** [osowskit/atlassian-github-app-addon#53]
Landed on this app from Atlassian [community page](https://community.atlassian.com/t5/Jira-questions/Github-Integration-with-Next-Gen/qaq-p/1094227) but could not get it to work with the error in the attachment
![image](https://user-images.githubusercontent.com/2154248/75105511-174a5380-5679-11ea-9807-d45920eb7132.jpeg)
![image](https://user-images.githubusercontent.com/2154248/75105514-1dd8cb00-5679-11ea-9234-413853b79876.jpeg)
![image](https://user-images.githubusercontent.com/2154248/75105525-3fd24d80-5679-11ea-9347-4ac126451b12.jpeg)
![image](https://user-images.githubusercontent.com/2154248/75105527-4365d480-5679-11ea-986d-715b6d6e6509.jpeg)

**Comment by osowskit** [comment]
@dattachandan could you select the 'Connect to GitHub' link and open it in a new Window/tab and let me know if this helps? It would also be good to check the browsers error console for any messages.

**Comment by osowskit** [comment]
@dattachandan please let me know how I can help you resolve this issue

**Comment by dattachandan** [comment]
Hi Tom, 

Sorry for the delay in replying. 

Test System: OS X 10.12.6, Safari 12.1.2 and Chrome Version 80.0.3987.122

It works on Chrome past the "installing or configuring this plugin" screen, but not on Safari.  

Screenshots below for Safari
![Screen Shot 2020-03-01 at 2 44 17 PM](https://user-images.githubusercontent.com/2154248/75618049-270fed80-5bcd-11ea-8a91-e18289fc7df7.png)


Screenshots below for Chrome
![image](https://user-images.githubusercontent.com/2154248/75618020-9b965c80-5bcc-11ea-901e-feffb473d7ec.jpeg)
![image](https://user-images.githubusercontent.com/2154248/75618022-a0f3a700-5bcc-11ea-9ce0-b0c6034efecb.jpeg)

![image](https://user-images.githubusercontent.com/2154248/75618026-b1a41d00-5bcc-11ea-8b96-027c8b899ab6.jpeg)


On Chrome after the completion of the installation, I can't see the plugin integration working on JIRA in the development panel
![image](https://user-images.githubusercontent.com/2154248/75618030-ced8eb80-5bcc-11ea-81b2-36aeaad2c2e0.jpeg)
![image](https://user-images.githubusercontent.com/2154248/75618033-d4cecc80-5bcc-11ea-89ed-2f7e1b810ac6.jpeg)

**Comment by dattachandan** [comment]
Sorry accidentally closed the ticket

**Comment by osowskit** [comment]
Thanks for reporting this. 

It looks like this is broken on safari. I'll see about fixing this soon but chrome should work until I've identified the issue.

**Comment by osowskit** [comment]
@dattachandan this should be resolved now. It appears this was more widespread than I expected.

**Comment by osowskit** [comment]
This issue was caused by [this](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html). @dattachandan if you find this working now, please reconsider the review you left for this plugin 🙏
