### ISSUE TITLE
Looking for collaborators

### ISSUE THREAD

**Issue by osowskit** [osowskit/atlassian-github-app-addon#54]
@gleb-gusev I saw you fork this repo. This doesn't contain the lastest code - I hadn't had any serious requests to improve this. Let me know if you are planning on adding support for any of the open issues in this repo and I can gladly help (and push the latest code)

**Comment by amumm** [comment]
@osowskit I would like the ability to add a branch with a custom name without having a "/" at the end of the JIRA tag. The reason being is this creates a folder in source tree. If you can point me in the right direction I would gladly make the PR. eg. ST-103/something  <-- this is the current option I would like to have eg. ST-103"whatever I want at this point"

**Comment by osowskit** [comment]
This should now be possible.
