### ISSUE TITLE
Safari has "trouble connecting to GitHub Development."

### ISSUE THREAD

**Issue by mjvdvlugt** [osowskit/atlassian-github-app-addon#55]
I'm very happy with the Jira plugin you made! I works like a charm when we use Jira in Google Chrome, but I see it currently doesn't work in Safari on macOS Catalina (10.15.3). It shows the following error message:
<img width="323" alt="Schermafbeelding 2020-03-18 om 11 25 40" src="https://user-images.githubusercontent.com/22216538/76950985-33a17f00-690b-11ea-98b3-0e1ba7de6fe7.png">
The info screen shows the warning:
<img width="429" alt="Schermafbeelding 2020-03-18 om 11 29 26" src="https://user-images.githubusercontent.com/22216538/76951358-d9ed8480-690b-11ea-8e36-967846fe2e52.png">

In Chrome and Safari, I made sure I'm logged in to the same Github account, and I'm testing on the same Jira instance (even same issue). Also I tested with a colleague, he experienced the same. What information can I add to help debug this?

**Comment by osowskit** [comment]
@mjvdvlugt thanks for reporting this. I'll take a look. It was working with the latest version two weeks ago but will investigate

**Comment by odoedkiy** [comment]
@mjvdvlugt I was able to reproduce this when I loaded the page after upgrading. After refreshing the page (and inspecting the iframe element) this went away. Does a hard page reset resolve this?

If not, could you visit (https://atlassian-github-app-addon.herokuapp.com/logout) in a separate Safari tab.

**Comment by mjvdvlugt** [comment]
@odoedkiy Refreshing the page didn't resolve it. I opened the "logout" link in a separate tab (this showed the "Connect to GitHub" page) and refreshed Jira again. Now "Open GitHub Development" also showed the "Connect to GitHub", which after clicking opened and closed the pop-up. After a page refresh the plugin showed my repos!
But... Closing and opening Safari introduced the issue again. (need to open "logout" and refresh to make it work again)

**Comment by odoedkiy** [comment]
> But... Closing and opening Safari introduced the issue again. (need to open "logout" and refresh to make it work again)

Thanks. This is super helpful. I'll need to reach out to Atlassian's support as this appears to be something with their JS library 🤔

**Comment by odoedkiy** [comment]
@mjvdvlugt I was able to track this down with Atlassian's help. I've pushed code to fix this. There is still a known issue where the initial log in requires refreshing that page. I've also discovered another where it seems the cookies are deleted by default when closing Safari, so this requires connecting to GitHub when restarting Safari.

Let me know how this works for you

**Comment by osowskit** [comment]
@mjvdvlugt let me know if you can confirm this is working for you

**Comment by mjvdvlugt** [comment]
Hi @osowskit yes this is working now!! I've also let my colleague test it, and it also works for him!!
