### ISSUE TITLE
add a branch with a custom name without having a "/" at the end of the JIRA tag.

### ISSUE THREAD

**Issue by osowskit** [osowskit/atlassian-github-app-addon#56]
@osowskit I would like the ability to add a branch with a custom name without having a "/" at the end of the JIRA tag. The reason being is this creates a folder in source tree. If you can point me in the right direction I would gladly make the PR. 

**eg.**

`ST-103/something` <-- this is the current option 
`ST-103whatever I want at this point` <-- I would like to have

_Originally posted by @amumm in https://github.com/osowskit/atlassian-github-app-addon/issues/54#issuecomment-601864031_

**Comment by osowskit** [comment]
It certainly shouldn't have a trailing '/'. Let me take a look and get back to you if i have any questions.

@amumm

**Comment by amumm** [comment]
Fantastic thanks :)

**Comment by osowskit** [comment]
I misread the original post. The best solution would be to add a new option that will allow setting a custom delimiter as well. Any chance you could also log a request for source tree to handle `/` characters in branch names?

**Comment by amumm** [comment]
It is my understanding that source tree does this by design. Quite frankly a new option would be fine by me because I would prefer to not have the `/` in the name in the first place.

**Comment by osowskit** [comment]
I shifted the delimiter so it is in the textfield. You should be able to delete/modify it now. Let me know if you have any trouble with this.

**Comment by amumm** [comment]
That worked. Thanks a bunch.

**Comment by osowskit** [comment]
Please review this plugin when you get a chance.
