### ISSUE TITLE
Branch creation and work with official GitHub Plugin

### ISSUE THREAD

**Issue by stgeipel** [osowskit/atlassian-github-app-addon#60]
Hey @osowskit,

we would work with the [official GitHub Addon](https://github.com/integrations/jira/blob/master/README.md#link-issues-in-github) and your Addon.
When we create a branch with your Plugin the name is for example **TEST-1**. The App from Github does not trigger and does not show a branch.
If i create a branch with the name **TEST-1** in Github or with Git it triggers and shows me under Development in the Jira Issue

Steps to reproduce 

[Install Github Addon](https://marketplace.atlassian.com/apps/1219592/github-for-jira?hosting=cloud&tab=overview)
Install your Addon
Create an Jira Issue
Create an Branch with your Addon

There is no entry under Development

Steps with Github

[Install Github Addon](https://marketplace.atlassian.com/apps/1219592/github-for-jira?hosting=cloud&tab=overview)
Install your Addon
Create an Jira Issue
Create an Branch in Github with Name of Issue

There is an entry under Development
![image](https://user-images.githubusercontent.com/46808966/86463071-19aa7180-bd2d-11ea-8f3e-acd9ee201f4e.png)

**Comment by osowskit** [comment]
I believe this is the same issue as described in #52. GitHub doesn't send branch creation events between apps. I've reached out to their support but would recommend asking the GitHub plugin team if they can help.

**Comment by osowskit** [comment]
> There is an entry under Development

Branches created using the issue key (ABC-123/mybranch) in the branch name will show up in a separate tab 'GitHub Development'. This plugin only displays branches with this format.

Due to a limitation with how GitHub does not send events between apps, these GitHub plugin may not work as expected. I would reach out to their plugin support to get these to show up.

**Comment by stgeipel** [comment]
Thanks for your help. I would try to get an answer from the github plugin support. 

Have a nice day ! 😀

**Comment by stgeipel** [comment]
thanks for the quick reply and the explanation. i will try to contact the support of the github plugin.

have a nice day :)
