### ISSUE TITLE
Can't connect right after install

### ISSUE THREAD

**Issue by Naxit** [osowskit/atlassian-github-app-addon#62]
After I've installed this addon, I had (almost) this message in the "Configure" page on Jira : "inactive or canceled".

Response from osowskit : "Org Admin sometimes are required to add plugin."

**Comment by osowskit** [comment]
Could you provide a screenshot? There is known behavior in Jira where it takes minutes (sometimes hours) for them to create a license for the trial. It would be helpful to determine if this the problem.

**Comment by Naxit** [comment]
I already uninstall all the addons that I tested and didn’t worked.
I had a meeting between the installation and my last test which lasted an hour and a half.

Sorry if I can’t help more but I’m out of time at the moment :/


Cordialement,

Axel CRÉMONT
Design & Front-end

[cid:image001.png@01D6884E.997952A0]
[cid:image002.png@01D6884E.997952A0]
  Aexae
[cid:image003.png@01D6884E.997952A0]
+33 (0)1 60 92 18 58
[cid:image004.png@01D6884E.997952A0]
www.aexae.fr<http://www.aexae.fr/>
[cid:image005.png@01D6884E.997952A0]
1, rue de Terre Neuve, bât. i
91940 Les Ulis
