### ISSUE TITLE
Unable to connect Jira

### ISSUE THREAD

**Issue by pimduijst** [osowskit/atlassian-github-app-addon#63]
When I click on 'Connect to Github' in my Jira env I get a popup showing me this...

<img width="1285" alt="Screenshot 2021-02-16 at 16 13 38" src="https://user-images.githubusercontent.com/1483463/108082928-db22b680-7072-11eb-95eb-7c68ebd1f67b.png">

Please help me any further.

**Comment by osowskit** [comment]
Can you email me to get more information about your account? osowskit@osowskit.com

**Comment by osowskit** [comment]
There appears to have been a change made by GitHub that is incompatible w/ one of the libraries being used : https://github.com/octokit/octokit.rb/issues/1325

**Comment by osowskit** [comment]
@pimduijst i've updated the app to fix this. Apologies for the inconvenience and thank you for reporting this.

**Comment by pimduijst** [comment]
Thanks for the quick action. It all works perfectly now.
