### ISSUE TITLE
Lowercase branch names required for Pantheon

### ISSUE THREAD

**Issue by Fluke-KevinD** [osowskit/atlassian-github-app-addon#64]
Hi, we have the need to match branch names with Pantheon in order to spin up what they call "multi-dev's" from those branches: https://pantheon.io/docs/multidev#getting-started. 

Our Github account synchronizes with Pantheon's git repo, and they have to match.

Would it be possible to control the branch names to be lowercase?

Thank you!

**Comment by osowskit** [comment]
It would be possible. Could you provide examples of what these would look like- is this simply translating the existing strings to lowercase?

I haven't heard any other requests for this and wasn't planning on adding new features in the near future. If this blocks purchasing the software, it'd be helpful knowing how many seats your company would purchase of the plugin to help determine if this is worth the engineering work.

**Comment by Fluke-KevinD** [comment]
Hi @osowskit , thanks for your response!

Example: "**abc-1234567**"

> Multidev branch names must be all lowercase, less than 11 characters, and may contain a dash (-).

Our usage in Jira Cloud would begin with ~10-12 users of the plugin but that would grow. 
My team manages dozens of websites under FORTIVE/Fluke (www.fluke.com) and we recently moved to Github Enterprise as the going standard for all repo's in the company. The value of your addon starts by letting developers create a branch name right from Jira that initiates Github actions to create Multidev's (dev websites) automatically on Pantheon.io. It's a missing part of our CI/CD plan to automate an array of development procedures.

Thank you!

**Comment by osowskit** [comment]
Thanks for the additional information. It's not possible to support Github Enterprise last time I checked so it's unlikely you'll be able to use this plugin.

**Comment by Fluke-KevinD** [comment]
Ah, that's a blocker then. Thanks!
