### ISSUE TITLE
Security Self-Assessment Program

### ISSUE THREAD

**Issue by fluidnumericsguy** [osowskit/atlassian-github-app-addon#65]
Are there plans to put this add-on through the Jira Marketplace Security Self-Assessment Program?

**Comment by osowskit** [comment]
Great question. I had applies a few years back and never heard back from Atlassian. There is information about security here: https://atlassian-github-app-addon.herokuapp.com/privacy.html 

 Given the light-weight nature of the plugin and limited permissions required, many of the requirements/controls wouldn't apply. Specifically, this app doesn't have read/write access to Jira, the service was designed to be ephemeral and doesn't need to store any client data (outside of cached data for performance), and the infrastructure hosting the service is SOC II compliant.  
 
 Let me know if you have any particular concerns you'd like discussed
