### ISSUE TITLE
Failed to create branch

### ISSUE THREAD

**Issue by doniyor2109** [osowskit/atlassian-github-app-addon#66]
We have connected the plugin with our JIRA dashboard and linked our GitHub repository. The repositories are shown in the list but when we create branch, it is showing error saying "Not Found".

When I click the create button it is sending POST request to this url https://createbranch.gitconnector.com/api/branch and the response is `{"status":404,"message":"Not Found"}`. I have checked the payload which is being sent and they are fine.

![Screen Shot 2021-08-10 at 17 17 10](https://user-images.githubusercontent.com/14192979/128865332-68750732-629c-4f3e-b92e-d6e8123346bf.png)

**Comment by osowskit** [comment]
The image and description doesn't appear to be for the this add on. Is it possible you are evaluating multiple plugins and having trouble with a separate one? Could you take a screenshot of the right side of an issue that shows each component?

**Comment by doniyor2109** [comment]
@osowskit Sorry. It looks I have submitted to wrong repository.  😄
