### ISSUE TITLE
Why does the plugin request access to read/write the source code?

### ISSUE THREAD

**Issue by meekrosoft** [osowskit/atlassian-github-app-addon#68]
Why does the plugin request access to read/write the source code?

![image](https://user-images.githubusercontent.com/145429/134492239-e3b1ed40-2ae1-4c27-b6fb-722470a54351.png)

This access requirement make it impossible for our company to use the plugin

**Comment by osowskit** [comment]
Unfortunately, GitHub doesn't have a specific permission to only read/write
branches. Any plugin that offers to manage branches via a GitHub App will
require this.

I'd suggest reaching out to GitHub and requesting they offer this granular
access.

Separately, let me know if you have any questions on access controls and
how access to the account is limited.
