### ISSUE TITLE
Is there a way to have BOTH gitflow (feature/ bugfix/ etc) and custom naming?

### ISSUE THREAD

**Issue by emcdaniel-sungage** [osowskit/atlassian-github-app-addon#70]
We're moving from Bitbucket to GitHub and want to take our naming standard with us. For example `feature/ENG-123-snake-case-version-of-ticket-summary`.

Is there a `branch_pattern` setting for this? 

Thanks.

**Comment by osowskit** [comment]
It's possible to add this as a custom branch naming option but haven't heard of other requests for this feature. It's something I may add if there are others interested in this naming strategy.

**Comment by osowskit** [comment]
@emcdaniel-sungage I've added a new `branch_pattern: 3` that will add the custom branch naming for the git flow pattern. Please have a look and let me know if you have any issues
