### ISSUE TITLE
Can't connect a repo from a JIRA ticket

### ISSUE THREAD

**Issue by soccer-coder** [osowskit/atlassian-github-app-addon#71]
After I opened the GitHub Development, it displayed a list of repos

<img width="486" alt="Screen Shot 2022-08-30 at 10 01 11 AM" src="https://user-images.githubusercontent.com/40770475/187496561-7793e4ac-d4a8-4931-baa3-cfb4abceefd7.png">

But when I clicked on one of the repos, it does not do anything.  As a result, we could not link a ticket to a repo, and create a branch for this JIRA ticket.

**Comment by osowskit** [comment]
Thank you for reporting this. I've been able to reproduce this and will investigate.

**Comment by osowskit** [comment]
@soccer-coder I believe I've resolved the issue. You may need to use the Clear Settings button to refresh the settings : https://atlassian-github-app-addon.herokuapp.com/logout
